### ISSUE TITLE
Fluentd crashes when watching namespace metadata

### ISSUE THREAD

**Issue by julienlefur** [fabric8io/fluent-plugin-kubernetes_metadata_filter#239]
The watch connection on the API Server seems to be closed regularly by one of the following : Kubeclient / http / apiserver

When no modifications are made on the namespaces, the namespace_watch_retry_count is constantly increasing due to this error:
`2020-06-26 11:59:04 +0000 [info]: #0 [filter_kube_metadata] Exception encountered parsing namespace watch event. The connection might have been closed. Sleeping for 128 seconds and resetting the namespace watcher.error reading from socket: Could not parse data
`

When the max is reached, Fluentd crashes and restarts.

https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/blob/940296bac92ac05b97654e156dcf16c1eacd21b5/lib/fluent/plugin/kubernetes_metadata_watch_namespaces.rb#L43-L55

The only way to reset the namespace_watch_retry_count is to make a change on a namespace so the function `reset_namespace_watch_retry_stats` is called. But when no modification are done on the namespace, fluentd crashes after 10 'connection closed' errors.

Would it be possible to catch the 'normal' connection close errors to avoid this behaviour?

It seems to be linked to this issue on Kubeclient: https://github.com/abonas/kubeclient/issues/273

**Comment by jcantrill** [comment]
fixed by https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/pull/247

**Comment by julienlefur** [comment]
@jcantrill I still have the same behaviour with the version 2.5.2
The connection to the api-server is closed regularly. The stat counter "namespace_watch_failures" is incremented until 10 and fluentd crashes.
I have a cronjob that runs to apply a change in a namespace in order to make fluentd reset this counter. The is a workaround to prevent fluentd to crash.
I'll keep you posted if I can dig deeper and find a few things.

**Comment by malmuzaini** [comment]
@jcantrill we upgraded and we still get the same issue! Can you please help
